/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthorRouteRouteImport } from './routes/_author/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSubmissionsRouteRouteImport } from './routes/_app/submissions/route'
import { Route as AppMyTeamRouteRouteImport } from './routes/_app/my-team/route'
import { Route as AuthorAuthorIndexRouteImport } from './routes/_author/author/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AuthAuthorLoginIndexRouteImport } from './routes/_auth/author-login/index'
import { Route as AppSubmissionsIndexRouteImport } from './routes/_app/submissions/index'
import { Route as AppPublishedManuscriptsIndexRouteImport } from './routes/_app/published-manuscripts/index'
import { Route as AppProspectiveAuthorsIndexRouteImport } from './routes/_app/prospective-authors/index'
import { Route as AppMyTeamIndexRouteImport } from './routes/_app/my-team/index'
import { Route as AppSubmissionsIdIndexRouteImport } from './routes/_app/submissions/$id/index'
import { Route as AppPublishedManuscriptsVolumeIndexRouteImport } from './routes/_app/published-manuscripts/$volume/index'
import { Route as AppMyTeamAddUserIndexRouteImport } from './routes/_app/my-team/add-user/index'
import { Route as AppPublishedManuscriptsVolumeIssueIndexRouteImport } from './routes/_app/published-manuscripts/$volume/$issue/index'
import { Route as AppMyTeamEditUserRoleIdRouteImport } from './routes/_app/my-team/edit-user.$role.$id'

const AuthorRouteRoute = AuthorRouteRouteImport.update({
  id: '/_author',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSubmissionsRouteRoute = AppSubmissionsRouteRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMyTeamRouteRoute = AppMyTeamRouteRouteImport.update({
  id: '/my-team',
  path: '/my-team',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthorAuthorIndexRoute = AuthorAuthorIndexRouteImport.update({
  id: '/author/',
  path: '/author/',
  getParentRoute: () => AuthorRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/_auth/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthorLoginIndexRoute = AuthAuthorLoginIndexRouteImport.update({
  id: '/_auth/author-login/',
  path: '/author-login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSubmissionsIndexRoute = AppSubmissionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSubmissionsRouteRoute,
} as any)
const AppPublishedManuscriptsIndexRoute =
  AppPublishedManuscriptsIndexRouteImport.update({
    id: '/published-manuscripts/',
    path: '/published-manuscripts/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppProspectiveAuthorsIndexRoute =
  AppProspectiveAuthorsIndexRouteImport.update({
    id: '/prospective-authors/',
    path: '/prospective-authors/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppMyTeamIndexRoute = AppMyTeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMyTeamRouteRoute,
} as any)
const AppSubmissionsIdIndexRoute = AppSubmissionsIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => AppSubmissionsRouteRoute,
} as any)
const AppPublishedManuscriptsVolumeIndexRoute =
  AppPublishedManuscriptsVolumeIndexRouteImport.update({
    id: '/published-manuscripts/$volume/',
    path: '/published-manuscripts/$volume/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppMyTeamAddUserIndexRoute = AppMyTeamAddUserIndexRouteImport.update({
  id: '/add-user/',
  path: '/add-user/',
  getParentRoute: () => AppMyTeamRouteRoute,
} as any)
const AppPublishedManuscriptsVolumeIssueIndexRoute =
  AppPublishedManuscriptsVolumeIssueIndexRouteImport.update({
    id: '/published-manuscripts/$volume/$issue/',
    path: '/published-manuscripts/$volume/$issue/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppMyTeamEditUserRoleIdRoute = AppMyTeamEditUserRoleIdRouteImport.update({
  id: '/edit-user/$role/$id',
  path: '/edit-user/$role/$id',
  getParentRoute: () => AppMyTeamRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/my-team': typeof AppMyTeamRouteRouteWithChildren
  '/submissions': typeof AppSubmissionsRouteRouteWithChildren
  '/': typeof AppIndexRoute
  '/my-team/': typeof AppMyTeamIndexRoute
  '/prospective-authors': typeof AppProspectiveAuthorsIndexRoute
  '/published-manuscripts': typeof AppPublishedManuscriptsIndexRoute
  '/submissions/': typeof AppSubmissionsIndexRoute
  '/author-login': typeof AuthAuthorLoginIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/author': typeof AuthorAuthorIndexRoute
  '/my-team/add-user': typeof AppMyTeamAddUserIndexRoute
  '/published-manuscripts/$volume': typeof AppPublishedManuscriptsVolumeIndexRoute
  '/submissions/$id': typeof AppSubmissionsIdIndexRoute
  '/my-team/edit-user/$role/$id': typeof AppMyTeamEditUserRoleIdRoute
  '/published-manuscripts/$volume/$issue': typeof AppPublishedManuscriptsVolumeIssueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/my-team': typeof AppMyTeamIndexRoute
  '/prospective-authors': typeof AppProspectiveAuthorsIndexRoute
  '/published-manuscripts': typeof AppPublishedManuscriptsIndexRoute
  '/submissions': typeof AppSubmissionsIndexRoute
  '/author-login': typeof AuthAuthorLoginIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/author': typeof AuthorAuthorIndexRoute
  '/my-team/add-user': typeof AppMyTeamAddUserIndexRoute
  '/published-manuscripts/$volume': typeof AppPublishedManuscriptsVolumeIndexRoute
  '/submissions/$id': typeof AppSubmissionsIdIndexRoute
  '/my-team/edit-user/$role/$id': typeof AppMyTeamEditUserRoleIdRoute
  '/published-manuscripts/$volume/$issue': typeof AppPublishedManuscriptsVolumeIssueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_author': typeof AuthorRouteRouteWithChildren
  '/_app/my-team': typeof AppMyTeamRouteRouteWithChildren
  '/_app/submissions': typeof AppSubmissionsRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/my-team/': typeof AppMyTeamIndexRoute
  '/_app/prospective-authors/': typeof AppProspectiveAuthorsIndexRoute
  '/_app/published-manuscripts/': typeof AppPublishedManuscriptsIndexRoute
  '/_app/submissions/': typeof AppSubmissionsIndexRoute
  '/_auth/author-login/': typeof AuthAuthorLoginIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_author/author/': typeof AuthorAuthorIndexRoute
  '/_app/my-team/add-user/': typeof AppMyTeamAddUserIndexRoute
  '/_app/published-manuscripts/$volume/': typeof AppPublishedManuscriptsVolumeIndexRoute
  '/_app/submissions/$id/': typeof AppSubmissionsIdIndexRoute
  '/_app/my-team/edit-user/$role/$id': typeof AppMyTeamEditUserRoleIdRoute
  '/_app/published-manuscripts/$volume/$issue/': typeof AppPublishedManuscriptsVolumeIssueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/my-team'
    | '/submissions'
    | '/'
    | '/my-team/'
    | '/prospective-authors'
    | '/published-manuscripts'
    | '/submissions/'
    | '/author-login'
    | '/login'
    | '/author'
    | '/my-team/add-user'
    | '/published-manuscripts/$volume'
    | '/submissions/$id'
    | '/my-team/edit-user/$role/$id'
    | '/published-manuscripts/$volume/$issue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/my-team'
    | '/prospective-authors'
    | '/published-manuscripts'
    | '/submissions'
    | '/author-login'
    | '/login'
    | '/author'
    | '/my-team/add-user'
    | '/published-manuscripts/$volume'
    | '/submissions/$id'
    | '/my-team/edit-user/$role/$id'
    | '/published-manuscripts/$volume/$issue'
  id:
    | '__root__'
    | '/_app'
    | '/_author'
    | '/_app/my-team'
    | '/_app/submissions'
    | '/_app/'
    | '/_app/my-team/'
    | '/_app/prospective-authors/'
    | '/_app/published-manuscripts/'
    | '/_app/submissions/'
    | '/_auth/author-login/'
    | '/_auth/login/'
    | '/_author/author/'
    | '/_app/my-team/add-user/'
    | '/_app/published-manuscripts/$volume/'
    | '/_app/submissions/$id/'
    | '/_app/my-team/edit-user/$role/$id'
    | '/_app/published-manuscripts/$volume/$issue/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthorRouteRoute: typeof AuthorRouteRouteWithChildren
  AuthAuthorLoginIndexRoute: typeof AuthAuthorLoginIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_author': {
      id: '/_author'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/submissions': {
      id: '/_app/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof AppSubmissionsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/my-team': {
      id: '/_app/my-team'
      path: '/my-team'
      fullPath: '/my-team'
      preLoaderRoute: typeof AppMyTeamRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_author/author/': {
      id: '/_author/author/'
      path: '/author'
      fullPath: '/author'
      preLoaderRoute: typeof AuthorAuthorIndexRouteImport
      parentRoute: typeof AuthorRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/author-login/': {
      id: '/_auth/author-login/'
      path: '/author-login'
      fullPath: '/author-login'
      preLoaderRoute: typeof AuthAuthorLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/submissions/': {
      id: '/_app/submissions/'
      path: '/'
      fullPath: '/submissions/'
      preLoaderRoute: typeof AppSubmissionsIndexRouteImport
      parentRoute: typeof AppSubmissionsRouteRoute
    }
    '/_app/published-manuscripts/': {
      id: '/_app/published-manuscripts/'
      path: '/published-manuscripts'
      fullPath: '/published-manuscripts'
      preLoaderRoute: typeof AppPublishedManuscriptsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/prospective-authors/': {
      id: '/_app/prospective-authors/'
      path: '/prospective-authors'
      fullPath: '/prospective-authors'
      preLoaderRoute: typeof AppProspectiveAuthorsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/my-team/': {
      id: '/_app/my-team/'
      path: '/'
      fullPath: '/my-team/'
      preLoaderRoute: typeof AppMyTeamIndexRouteImport
      parentRoute: typeof AppMyTeamRouteRoute
    }
    '/_app/submissions/$id/': {
      id: '/_app/submissions/$id/'
      path: '/$id'
      fullPath: '/submissions/$id'
      preLoaderRoute: typeof AppSubmissionsIdIndexRouteImport
      parentRoute: typeof AppSubmissionsRouteRoute
    }
    '/_app/published-manuscripts/$volume/': {
      id: '/_app/published-manuscripts/$volume/'
      path: '/published-manuscripts/$volume'
      fullPath: '/published-manuscripts/$volume'
      preLoaderRoute: typeof AppPublishedManuscriptsVolumeIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/my-team/add-user/': {
      id: '/_app/my-team/add-user/'
      path: '/add-user'
      fullPath: '/my-team/add-user'
      preLoaderRoute: typeof AppMyTeamAddUserIndexRouteImport
      parentRoute: typeof AppMyTeamRouteRoute
    }
    '/_app/published-manuscripts/$volume/$issue/': {
      id: '/_app/published-manuscripts/$volume/$issue/'
      path: '/published-manuscripts/$volume/$issue'
      fullPath: '/published-manuscripts/$volume/$issue'
      preLoaderRoute: typeof AppPublishedManuscriptsVolumeIssueIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/my-team/edit-user/$role/$id': {
      id: '/_app/my-team/edit-user/$role/$id'
      path: '/edit-user/$role/$id'
      fullPath: '/my-team/edit-user/$role/$id'
      preLoaderRoute: typeof AppMyTeamEditUserRoleIdRouteImport
      parentRoute: typeof AppMyTeamRouteRoute
    }
  }
}

interface AppMyTeamRouteRouteChildren {
  AppMyTeamIndexRoute: typeof AppMyTeamIndexRoute
  AppMyTeamAddUserIndexRoute: typeof AppMyTeamAddUserIndexRoute
  AppMyTeamEditUserRoleIdRoute: typeof AppMyTeamEditUserRoleIdRoute
}

const AppMyTeamRouteRouteChildren: AppMyTeamRouteRouteChildren = {
  AppMyTeamIndexRoute: AppMyTeamIndexRoute,
  AppMyTeamAddUserIndexRoute: AppMyTeamAddUserIndexRoute,
  AppMyTeamEditUserRoleIdRoute: AppMyTeamEditUserRoleIdRoute,
}

const AppMyTeamRouteRouteWithChildren = AppMyTeamRouteRoute._addFileChildren(
  AppMyTeamRouteRouteChildren,
)

interface AppSubmissionsRouteRouteChildren {
  AppSubmissionsIndexRoute: typeof AppSubmissionsIndexRoute
  AppSubmissionsIdIndexRoute: typeof AppSubmissionsIdIndexRoute
}

const AppSubmissionsRouteRouteChildren: AppSubmissionsRouteRouteChildren = {
  AppSubmissionsIndexRoute: AppSubmissionsIndexRoute,
  AppSubmissionsIdIndexRoute: AppSubmissionsIdIndexRoute,
}

const AppSubmissionsRouteRouteWithChildren =
  AppSubmissionsRouteRoute._addFileChildren(AppSubmissionsRouteRouteChildren)

interface AppRouteRouteChildren {
  AppMyTeamRouteRoute: typeof AppMyTeamRouteRouteWithChildren
  AppSubmissionsRouteRoute: typeof AppSubmissionsRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppProspectiveAuthorsIndexRoute: typeof AppProspectiveAuthorsIndexRoute
  AppPublishedManuscriptsIndexRoute: typeof AppPublishedManuscriptsIndexRoute
  AppPublishedManuscriptsVolumeIndexRoute: typeof AppPublishedManuscriptsVolumeIndexRoute
  AppPublishedManuscriptsVolumeIssueIndexRoute: typeof AppPublishedManuscriptsVolumeIssueIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppMyTeamRouteRoute: AppMyTeamRouteRouteWithChildren,
  AppSubmissionsRouteRoute: AppSubmissionsRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppProspectiveAuthorsIndexRoute: AppProspectiveAuthorsIndexRoute,
  AppPublishedManuscriptsIndexRoute: AppPublishedManuscriptsIndexRoute,
  AppPublishedManuscriptsVolumeIndexRoute:
    AppPublishedManuscriptsVolumeIndexRoute,
  AppPublishedManuscriptsVolumeIssueIndexRoute:
    AppPublishedManuscriptsVolumeIssueIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthorRouteRouteChildren {
  AuthorAuthorIndexRoute: typeof AuthorAuthorIndexRoute
}

const AuthorRouteRouteChildren: AuthorRouteRouteChildren = {
  AuthorAuthorIndexRoute: AuthorAuthorIndexRoute,
}

const AuthorRouteRouteWithChildren = AuthorRouteRoute._addFileChildren(
  AuthorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthorRouteRoute: AuthorRouteRouteWithChildren,
  AuthAuthorLoginIndexRoute: AuthAuthorLoginIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
